#!/usr/bin/env python3
"""
knowledge/render.py — renders the knowledge catalog views from knowledge/manifest.yaml.

Standard library only (no PyYAML, no pip). python3 ships with the Xcode Command
Line Tools that git itself needs on macOS, so anyone who can commit can run this.

Usage
    python3 knowledge/render.py                 # (re)write Knowledge-current.md and Knowledge-future.md
    python3 knowledge/render.py --check         # exit 1 when the views are stale, the manifest is
                                                #   invalid, a reference file has no row, or a file's
                                                #   provenance header disagrees with its row
    python3 knowledge/render.py --stamp         # insert the provenance header into any listed file
                                                #   that lacks one (idempotent)
    python3 knowledge/render.py --stdout current [--format terminal] [--instance-version v18.2] [--heading "Overlay: X"]
    python3 knowledge/render.py --stdout future  [--heading "Overlay: X"]
    python3 knowledge/render.py --manifest PATH ...   # any of the above against another manifest
                                                #   (an overlay's skills/knowledge-manifest/manifest.yaml)

Manifest format (a deliberately small YAML subset, so no parser install is needed)
    - a top-level list; each entry starts with "- id:" and continues with two-space-indented "key: value" lines
    - scalar values only; quote a value with double quotes when it contains ": " or starts with a
      special character; null / ~ / empty means null
    - full-line "# comments" and blank lines are ignored
    - see CONTRIBUTING.md for the field reference
"""
import argparse
import os
import re
import sys
from datetime import date

REQUIRED_FIELDS = ["id", "category", "title", "skill", "file", "source_url",
                   "rock_version", "tier", "status", "added", "notes"]
TIERS = ["measured", "traced", "summarized"]
STATUSES = ["current", "roadmap"]

# Category ids the manifest may use, in display order. An id not listed here still
# renders (labelled by its id) so renaming or adding a category never breaks the render.
CATEGORY_LABELS = {
    "community-docs": "Community Rock documentation (community.rockrms.com)",
    "lava": "Lava language",
    "rock-source": "Rock source (SparkDevNetwork/Rock)",
    "rock-schema": "Rock database schema",
    "rockshop-plugin": "Rock Shop plugins",
    "front-end": "Front-end behavior inside Rock blocks",
    "house": "House conventions and workbench skills",
    # Overlay categories
    "instance-facts": "Instance facts",
    "deviations": "Intentional deviations from stock behavior",
}
TIER_LABELS = {
    "measured": "Measured — tested in a live Rock instance, dated",
    "traced": "Traced — read from Rock source or official documentation, cited",
    "summarized": "Summarized — condensed from a URL, not yet verified",
}
STAMP_RE = re.compile(r"Provenance tier:\**\s*[`*]*(measured|traced|summarized)", re.IGNORECASE)
GENERATED_NOTE = "<!-- Generated by knowledge/render.py from knowledge/manifest.yaml. Do not edit by hand; edit the manifest and re-render. -->"


# --------------------------------------------------------------------------- parsing

def _unquote(v):
    if v is None:
        return None
    v = v.strip()
    if v in ("", "null", "~"):
        return None
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        inner = v[1:-1]
        if v[0] == '"':
            inner = inner.replace('\\"', '"').replace("\\\\", "\\")
        return inner
    return v


def parse_manifest(path):
    entries, current, errors = [], None, []
    with open(path, encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            m = re.match(r"^(\s*)(- )?([A-Za-z_][A-Za-z0-9_]*):(?:\s(.*))?$", line)
            if not m:
                errors.append(f"{path}:{lineno}: cannot parse line: {line!r}")
                continue
            indent, dash, key, value = m.groups()
            if dash:
                if indent != "":
                    errors.append(f"{path}:{lineno}: list items must start at column 0")
                current = {"_line": lineno}
                entries.append(current)
            elif current is None:
                errors.append(f"{path}:{lineno}: field before the first '- id:' entry")
                continue
            elif indent != "  ":
                errors.append(f"{path}:{lineno}: entry fields must be indented exactly two spaces")
            if current is not None:
                if key in current and key != "_line":
                    errors.append(f"{path}:{lineno}: duplicate field {key!r} in entry")
                current[key] = _unquote(value)
    return entries, errors


def validate(entries, errors, manifest_path):
    seen = set()
    for e in entries:
        where = f"{manifest_path}:{e['_line']}"
        for f in REQUIRED_FIELDS:
            if f not in e:
                errors.append(f"{where}: missing field {f!r}")
        eid = e.get("id")
        if not eid:
            errors.append(f"{where}: empty id")
        elif eid in seen:
            errors.append(f"{where}: duplicate id {eid!r}")
        else:
            seen.add(eid)
            if not re.match(r"^[a-z0-9][a-z0-9-]*$", eid):
                errors.append(f"{where}: id {eid!r} must be lowercase-hyphen")
        if e.get("tier") not in TIERS:
            errors.append(f"{where}: tier must be one of {TIERS}, got {e.get('tier')!r}")
        if e.get("status") not in STATUSES:
            errors.append(f"{where}: status must be one of {STATUSES}, got {e.get('status')!r}")
        if not e.get("title"):
            errors.append(f"{where}: empty title")
        if not e.get("category"):
            errors.append(f"{where}: empty category")
        added = e.get("added")
        if added and not re.match(r"^\d{4}-\d{2}-\d{2}$", added):
            errors.append(f"{where}: added must be YYYY-MM-DD, got {added!r}")
        if e.get("status") == "current" and not e.get("rock_version"):
            errors.append(f"{where}: rock_version is required (write 'unknown' when not recorded)")
    return errors


# --------------------------------------------------------------------------- paths

def plugin_root_for(manifest_path, override=None):
    if override:
        return os.path.abspath(override)
    # knowledge/manifest.yaml → one level up; skills/knowledge-manifest/manifest.yaml → two levels up.
    # Walk upward to the directory that holds .claude-plugin/plugin.json; fall back to one level up.
    d = os.path.abspath(os.path.dirname(manifest_path))
    probe = d
    for _ in range(4):
        if os.path.isfile(os.path.join(probe, ".claude-plugin", "plugin.json")):
            return probe
        probe = os.path.dirname(probe)
    return os.path.abspath(os.path.join(d, os.pardir))


def entry_file_path(e, root):
    if not e.get("file"):
        return None
    if e.get("skill"):
        return os.path.join(root, "skills", e["skill"], e["file"])
    return os.path.join(root, e["file"])


def entry_file_display(e):
    if not e.get("file"):
        return "—"
    rel = f"skills/{e['skill']}/{e['file']}" if e.get("skill") else e["file"]
    return f"[{e['file']}](../{rel})"


def reference_files(root):
    found = []
    skills_dir = os.path.join(root, "skills")
    if not os.path.isdir(skills_dir):
        return found
    for skill in sorted(os.listdir(skills_dir)):
        refs = os.path.join(skills_dir, skill, "references")
        if not os.path.isdir(refs):
            continue
        for dirpath, _dirs, files in os.walk(refs):
            for fn in sorted(files):
                if fn.endswith(".md") and fn != "README.md":
                    found.append(os.path.join(dirpath, fn))
    return found


# --------------------------------------------------------------------------- versions

def parse_version(s):
    if not s:
        return None
    m = re.search(r"v?(\d+(?:\.\d+)*)", s)
    if not m:
        return None
    return tuple(int(p) for p in m.group(1).split("."))


def newer_than(entry_version, instance_version):
    a, b = parse_version(entry_version), parse_version(instance_version)
    if a is None or b is None:
        return False
    n = max(len(a), len(b))
    a += (0,) * (n - len(a))
    b += (0,) * (n - len(b))
    return a > b


# --------------------------------------------------------------------------- rendering

def _cell(s):
    return (s or "—").replace("|", "\\|").replace("\n", " ")


def _source_cell(url):
    if not url:
        return "—"
    label = re.sub(r"^https?://", "", url)
    label = label if len(label) <= 48 else label[:45] + "…"
    return f"[{label}]({url})"


def category_order(cats):
    known = [c for c in CATEGORY_LABELS if c in cats]
    unknown = sorted(c for c in cats if c not in CATEGORY_LABELS)
    return known + unknown


def render_current(entries, heading=None, instance_version=None, plugin_label="the rockrms plugin"):
    cur = [e for e in entries if e.get("status") == "current"]
    out = []
    out.append(f"# {heading}" if heading else f"# What {plugin_label} knows")
    if not heading:
        out.append("")
        out.append(GENERATED_NOTE)
    out.append("")
    out.append(f"{len(cur)} documented entries, grouped by category and then by provenance tier. "
               "Every entry is a reference file (or a stated coverage claim) with a source and the Rock version it was verified on.")
    out.append("")
    out.append("| Tier | Meaning |")
    out.append("|---|---|")
    for t in TIERS:
        out.append(f"| `{t}` | {TIER_LABELS[t].split(' — ', 1)[1]} |")
    if instance_version:
        out.append("")
        out.append(f"Your instance runs Rock {instance_version}. Entries marked ⚠ were verified on a newer Rock version — treat them as unverified for your instance.")
    cats = {e["category"] for e in cur}
    for cat in category_order(cats):
        out.append("")
        out.append(f"## {CATEGORY_LABELS.get(cat, cat)}  `{cat}`")
        for tier in TIERS:
            rows = [e for e in cur if e["category"] == cat and e["tier"] == tier]
            if not rows:
                continue
            out.append("")
            out.append(f"### {tier}")
            out.append("")
            out.append("| Title | Skill | File | Rock version | Source | Notes |")
            out.append("|---|---|---|---|---|---|")
            for e in sorted(rows, key=lambda x: (x.get("skill") or "", x["title"].lower())):
                ver = e.get("rock_version") or "unknown"
                if instance_version and newer_than(ver, instance_version):
                    ver = f"⚠ {ver}"
                skill = f"`{e['skill']}`" if e.get("skill") else "—"
                out.append(f"| {_cell(e['title'])} | {skill} | {entry_file_display(e)} | {_cell(ver)} | {_source_cell(e.get('source_url'))} | {_cell(e.get('notes'))} |")
    out.append("")
    return "\n".join(out)


def render_future(entries, heading=None, plugin_label="the rockrms plugin"):
    road = [e for e in entries if e.get("status") == "roadmap"]
    out = []
    out.append(f"# {heading}" if heading else f"# What {plugin_label} plans to document next")
    if not heading:
        out.append("")
        out.append(GENERATED_NOTE)
    out.append("")
    if not road:
        out.append("Nothing is on the roadmap yet. To propose a topic, open a PR that adds a `status: roadmap` row to the manifest — CONTRIBUTING.md has the steps.")
        out.append("")
        return "\n".join(out)
    out.append(f"{len(road)} roadmap entries, in manifest order. Each becomes `status: current` when its reference file lands with a source, a tier, and a Rock version.")
    out.append("")
    for i, e in enumerate(road, 1):
        cat = CATEGORY_LABELS.get(e["category"], e["category"])
        bits = [f"{i}. **{e['title']}** — {cat}"]
        if e.get("skill"):
            bits.append(f"(skill `{e['skill']}`)")
        line = " ".join(bits)
        tail = []
        if e.get("notes"):
            tail.append(e["notes"])
        if e.get("source_url"):
            tail.append(f"source: {e['source_url']}")
        if tail:
            line += "  \n   " + " · ".join(tail)
        out.append(line)
    out.append("")
    return "\n".join(out)


def render_current_terminal(entries, heading=None, instance_version=None):
    """Compact view for a terminal: titles only, grouped by category then tier."""
    cur = [e for e in entries if e.get("status") == "current"]
    out = [heading or "Documented knowledge", ""]
    if instance_version:
        out.append(f"Your instance runs Rock {instance_version}. Entries marked ⚠ were verified on a newer Rock version — treat them as unverified for your instance.")
        out.append("")
    cats = {e["category"] for e in cur}
    for cat in category_order(cats):
        label = CATEGORY_LABELS.get(cat, cat)
        out.append(f"{'=' * 12} {label} {'=' * 12}")
        for tier in TIERS:
            rows = [e for e in cur if e["category"] == cat and e["tier"] == tier]
            if not rows:
                continue
            out.append(f"  [{tier}]")
            for e in sorted(rows, key=lambda x: (x.get("skill") or "", x["title"].lower())):
                ver = e.get("rock_version") or "unknown"
                flag = "⚠ " if instance_version and newer_than(ver, instance_version) else ""
                where = f"skill {e['skill']}" if e.get("skill") else (e.get("file") or "")
                out.append(f"    - {flag}{e['title']}  ({where}; Rock {ver})")
        out.append("")
    out.append(f"{len(cur)} entries. Tiers: measured = tested in a live Rock instance; traced = read from source or official docs and cited; summarized = condensed from a URL, not yet verified.")
    out.append("")
    return "\n".join(out)


def render_future_terminal(entries, heading=None):
    road = [e for e in entries if e.get("status") == "roadmap"]
    out = [heading or "Roadmap", ""]
    if not road:
        out.append("Nothing is on the roadmap yet. Propose a topic with a status: roadmap row in the manifest (see CONTRIBUTING.md).")
        out.append("")
        return "\n".join(out)
    for i, e in enumerate(road, 1):
        label = CATEGORY_LABELS.get(e["category"], e["category"])
        line = f"{i}. {label}: {e['title']}"
        if e.get("notes"):
            line += f" — {e['notes']}"
        out.append(line)
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- stamp

def stamp_text(e):
    ver = (e.get("rock_version") or "unknown").strip()
    if ver.lower() in ("unknown", ""):
        ver_phrase = "Rock version not recorded"
    elif ver.lower() in ("n/a", "na", "none"):
        ver_phrase = "house convention, no Rock version"
    else:
        ver_phrase = f"Rock {ver}"
    tail = {
        "measured": f"tested in a live Rock instance ({ver_phrase}).",
        "traced": f"read from source or official documentation and cited ({ver_phrase}).",
        "summarized": f"condensed from the cited source, **not yet verified** in Rock ({ver_phrase}).",
    }[e["tier"]]
    return f"> **Provenance tier:** `{e['tier']}` — {tail} Catalogued in the plugin's knowledge manifest; `rockrms-knowledge-current` lists every entry."


def stamp_file(path, e):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if STAMP_RE.search(text[:2000]):
        return False
    lines = text.split("\n")
    start = 0
    if lines and lines[0].strip() == "---":            # skip YAML frontmatter (SKILL.md)
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                start = i + 1
                break
    insert_at = start
    for i in range(start, min(len(lines), start + 5)):  # stamp goes right after the H1 when there is one
        if lines[i].startswith("# "):
            insert_at = i + 1
            break
    after_h1 = insert_at > start or (insert_at < len(lines) and insert_at > 0 and lines[insert_at - 1].startswith("# "))
    block = ["", stamp_text(e), ""] if after_h1 else [stamp_text(e), ""]
    lines[insert_at:insert_at] = block
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return True


# --------------------------------------------------------------------------- checks

def check(entries, root, manifest_path):
    problems = []
    listed = {}
    for e in entries:
        p = entry_file_path(e, root)
        if p is None:
            continue
        if not os.path.isfile(p):
            problems.append(f"{e['id']}: file not found: {os.path.relpath(p, root)}")
            continue
        listed[os.path.abspath(p)] = e
        with open(p, encoding="utf-8") as fh:
            head = fh.read(2000)
        m = STAMP_RE.search(head)
        if not m:
            problems.append(f"{e['id']}: {os.path.relpath(p, root)} has no 'Provenance tier:' header (run --stamp)")
        elif m.group(1).lower() != e["tier"]:
            problems.append(f"{e['id']}: header says tier {m.group(1)!r} but manifest says {e['tier']!r}: {os.path.relpath(p, root)}")
    for p in reference_files(root):
        if os.path.abspath(p) not in listed:
            problems.append(f"reference file has no manifest row: {os.path.relpath(p, root)}")
    return problems


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--manifest", default=None, help="path to the manifest (default: knowledge/manifest.yaml next to this script)")
    ap.add_argument("--root", default=None, help="plugin root (default: two levels above the manifest)")
    ap.add_argument("--check", action="store_true", help="verify instead of write; exit 1 on any problem")
    ap.add_argument("--stamp", action="store_true", help="insert missing provenance headers into listed files")
    ap.add_argument("--stdout", choices=["current", "future"], help="print one view to stdout instead of writing files")
    ap.add_argument("--heading", default=None, help="override the H1 (used for overlay sections)")
    ap.add_argument("--instance-version", default=None, help="the Rock version the reader's instance runs, e.g. v18.2")
    ap.add_argument("--format", choices=["markdown", "terminal"], default="markdown", help="with --stdout: the GitHub table (markdown) or a compact title list (terminal)")
    args = ap.parse_args(argv)

    here = os.path.dirname(os.path.abspath(__file__))
    manifest = os.path.abspath(args.manifest or os.path.join(here, "manifest.yaml"))
    if not os.path.isfile(manifest):
        print(f"manifest not found: {manifest}", file=sys.stderr)
        return 2
    root = plugin_root_for(manifest, args.root)
    entries, errors = parse_manifest(manifest)
    errors = validate(entries, errors, manifest)
    if errors:
        for err in errors:
            print(f"ERROR {err}", file=sys.stderr)
        return 1

    if args.stdout:
        if args.format == "terminal":
            text = render_current_terminal(entries, args.heading, args.instance_version) if args.stdout == "current" else render_future_terminal(entries, args.heading)
        else:
            text = render_current(entries, args.heading, args.instance_version) if args.stdout == "current" else render_future(entries, args.heading)
        sys.stdout.write(text)
        return 0

    if args.stamp:
        n = 0
        for e in entries:
            p = entry_file_path(e, root)
            if p and os.path.isfile(p) and stamp_file(p, e):
                n += 1
                print(f"stamped {os.path.relpath(p, root)}")
        print(f"{n} file(s) stamped")
        return 0

    out_dir = os.path.dirname(manifest)
    ships_views = os.path.basename(out_dir) == "knowledge"   # overlays render at runtime and ship no views
    targets = {
        os.path.join(out_dir, "Knowledge-current.md"): render_current(entries),
        os.path.join(out_dir, "Knowledge-future.md"): render_future(entries),
    }
    if args.check:
        problems = check(entries, root, manifest)
        for path, text in (targets.items() if ships_views else []):
            if not os.path.isfile(path):
                problems.append(f"missing rendered view: {os.path.relpath(path, root)} (run render.py)")
                continue
            with open(path, encoding="utf-8") as fh:
                if fh.read() != text:
                    problems.append(f"stale rendered view: {os.path.relpath(path, root)} (run render.py and commit the result)")
        for p in problems:
            print(f"ERROR {p}", file=sys.stderr)
        if problems:
            return 1
        print(f"knowledge catalog OK: {len(entries)} entries, {'views current, ' if ships_views else ''}every reference file listed and stamped")
        return 0

    if not ships_views:
        print("this manifest is rendered at runtime (overlay); nothing to write — use --stdout or --check", file=sys.stderr)
        return 2
    for path, text in targets.items():
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {os.path.relpath(path, root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
